name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows: [Java CI]
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: v1v/otel-export-trace-action@v2
        with:
          otlpEndpoint: "${{ secrets.OPENTELEMETRY_ENDPOINT }}"
          otlpHeaders: "${{ secrets.OPENTELEMETRY_HEADER }}"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
